@implementation KmlManagerInterface

+ (id)interface
{
  void *v2;
  uint64_t v3;
  uint64_t v4;
  uint64_t v5;
  uint64_t v6;
  uint64_t v7;
  uint64_t v8;
  uint64_t v9;
  NSSet *v10;
  void *v11;
  void *v12;
  uint64_t v13;
  uint64_t v14;
  uint64_t v15;
  uint64_t v16;
  uint64_t v17;
  uint64_t v18;
  uint64_t v19;
  uint64_t v20;
  uint64_t v21;
  NSSet *v22;
  void *v23;
  void *v24;
  void *v25;
  uint64_t v26;
  uint64_t v27;
  uint64_t v28;
  uint64_t v29;
  uint64_t v30;
  uint64_t v31;
  uint64_t v32;
  NSSet *v33;
  void *v34;
  uint64_t v35;
  uint64_t v36;
  uint64_t v37;
  uint64_t v38;
  uint64_t v39;
  NSSet *v40;
  void *v41;
  uint64_t v43;
  uint64_t v44;
  uint64_t v45;
  uint64_t v46;
  uint64_t v47;
  uint64_t v48;
  uint64_t v49;
  uint64_t v50;
  uint64_t v51;
  uint64_t v52;
  uint64_t v53;
  uint64_t v54;
  uint64_t v55;
  uint64_t v56;
  uint64_t v57;
  uint64_t v58;
  void *v59;
  void *v60;
  void *v61;
  void *v62;

  v2 = (void *)objc_claimAutoreleasedReturnValue(+[NSXPCInterface interfaceWithProtocol:](NSXPCInterface, "interfaceWithProtocol:", &OBJC_PROTOCOL___KmlManagerProtocol));
  v3 = objc_opt_class(NSString);
  v4 = objc_opt_class(NSData);
  v5 = objc_opt_class(NSError);
  v6 = objc_opt_class(NSArray);
  v7 = objc_opt_class(NSNumber);
  v8 = objc_opt_class(NSUUID);
  v9 = objc_opt_class(DAKeyInformation);
  v10 = +[NSSet setWithObjects:](NSSet, "setWithObjects:", v3, v4, v5, v6, v7, v8, v9, objc_opt_class(DAAlishaKeyEncryptedRequest), 0);
  v61 = (void *)objc_claimAutoreleasedReturnValue(v10);
  v60 = (void *)objc_claimAutoreleasedReturnValue(+[NSXPCInterface interfaceWithProtocol:](NSXPCInterface, "interfaceWithProtocol:", &OBJC_PROTOCOL___KmlOwnerPairingCallbacks));
  objc_msgSend(v60, "setClasses:forSelector:argumentIndex:ofReply:", v61, "handleKeyPairingCompletionResult:keyInformation:trackingRequest:", 1, 0);
  objc_msgSend(v2, "setInterface:forSelector:argumentIndex:ofReply:", v60, "queueOwnerPairingSession:callback:", 0, 0);
  v59 = (void *)objc_claimAutoreleasedReturnValue(+[NSXPCInterface interfaceWithProtocol:](NSXPCInterface, "interfaceWithProtocol:", &OBJC_PROTOCOL___KmlOwnerPairingProtocol));
  v62 = v2;
  objc_msgSend(v2, "setInterface:forSelector:argumentIndex:ofReply:", v59, "queueOwnerPairingSession:callback:", 0, 1);
  v11 = (void *)objc_claimAutoreleasedReturnValue(+[NSXPCInterface interfaceWithProtocol:](NSXPCInterface, "interfaceWithProtocol:", &OBJC_PROTOCOL___KmlSessionCallbacks));
  objc_msgSend(v2, "setInterface:forSelector:argumentIndex:ofReply:", v11);

  v12 = (void *)objc_claimAutoreleasedReturnValue(+[NSXPCInterface interfaceWithProtocol:](NSXPCInterface, "interfaceWithProtocol:", &OBJC_PROTOCOL___KmlKeySharingProtocol));
  v56 = objc_opt_class(NSArray);
  v55 = objc_opt_class(NSString);
  v54 = objc_opt_class(NSData);
  v53 = objc_opt_class(NSError);
  v51 = objc_opt_class(NSUUID);
  v49 = objc_opt_class(NSNumber);
  v47 = objc_opt_class(DAKeySharingConfiguration);
  v45 = objc_opt_class(DAKeyInformation);
  v13 = objc_opt_class(DAAlishaKeyEncryptedRequest);
  v14 = objc_opt_class(DAKeySharingInvitationData);
  v15 = objc_opt_class(DAKeyInvitationRequestConfig);
  v16 = objc_opt_class(DAKeyBindingAttestationRequestData);
  v17 = objc_opt_class(DACarKeySharingMessage);
  v18 = objc_opt_class(DACarKeyGenericCrossPlatformSharingData);
  v19 = objc_opt_class(DACarKeyAdditionalCrossPlatformSharingData);
  v20 = objc_opt_class(DACarKeyPrivateCrossPlatformSharingData);
  v21 = objc_opt_class(DAShareRecipientResult);
  v22 = +[NSSet setWithObjects:](NSSet, "setWithObjects:", v56, v55, v54, v53, v51, v49, v47, v45, v13, v14, v15, v16, v17, v18, v19, v20, v21,
          objc_opt_class(DAShareInitiatorResult),
          0);
  v23 = (void *)objc_claimAutoreleasedReturnValue(v22);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "sendSharingInviteForKeyIdentifier:toIdsIdentifier:auth:config:completionHandler:", 3, 0);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "sendSharingInviteForKeyIdentifier:toIdsIdentifier:auth:config:completionHandler:", 0, 1);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "sendSilentSharingInviteForKeyIdentifier:config:groupIdentifier:completionHandler:", 1, 0);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "sendSilentSharingInviteForKeyIdentifier:config:groupIdentifier:completionHandler:", 0, 1);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "acceptSharingInvitationWithIdentifier:passcode:productPlanIdentifier:completionHandler:", 2, 0);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "acceptSharingInvitationWithIdentifier:passcode:productPlanIdentifier:completionHandler:", 0, 1);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "requestInviteWithConfig:completionHandler:", 0, 0);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "getPreTrackRequestForInvitationWithIdentifier:completionHandler:", 0, 1);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "createSharingInvitationsForKeyIdentifier:friendIdentifier:auth:ourBindingAttestation:config:completionHandler:", 4, 0);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "createSharingInvitationsForKeyIdentifier:friendIdentifier:auth:ourBindingAttestation:config:completionHandler:", 0, 1);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "createSilentSharingInvitationWithGroupIdentifier:completionHandler:", 0, 0);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "createSilentSharingInvitationWithGroupIdentifier:completionHandler:", 0, 1);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "acceptSharingInvitation:withIdentifier:fromMailboxIdentifier:passcode:productPlanIdentifier:completionHandler:", 0, 0);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "acceptSharingInvitation:withIdentifier:fromMailboxIdentifier:passcode:productPlanIdentifier:completionHandler:", 4, 0);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "acceptSharingInvitation:withIdentifier:fromMailboxIdentifier:passcode:productPlanIdentifier:completionHandler:", 0, 1);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "startShareAcceptanceFlowWithInvitation:fromMailboxIdentifier:completionHandler:", 0, 0);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "handleRecipientMessage:forInvitationIdentifier:completionHandler:", 0, 0);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "handleRecipientMessage:forInvitationIdentifier:completionHandler:", 0, 1);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "handleInitiatorMessage:forInvitationIdentifier:completionHandler:", 0, 0);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "handleInitiatorMessage:forInvitationIdentifier:completionHandler:", 0, 1);
  objc_msgSend(v12, "setClasses:forSelector:argumentIndex:ofReply:", v23, "retryPasscode:forInvitationIdentifier:completionHandler:", 0, 1);
  objc_msgSend(v62, "setInterface:forSelector:argumentIndex:ofReply:", v12, "queueSharingSession:callback:", 0, 1);
  v24 = (void *)objc_claimAutoreleasedReturnValue(+[NSXPCInterface interfaceWithProtocol:](NSXPCInterface, "interfaceWithProtocol:", &OBJC_PROTOCOL___KmlSessionCallbacks));
  objc_msgSend(v62, "setInterface:forSelector:argumentIndex:ofReply:", v24);

  v25 = (void *)objc_claimAutoreleasedReturnValue(+[KmlKeyManagementInterface interface](KmlKeyManagementInterface, "interface"));
  v52 = objc_opt_class(NSArray);
  v50 = objc_opt_class(NSString);
  v48 = objc_opt_class(NSData);
  v46 = objc_opt_class(NSError);
  v44 = objc_opt_class(NSUUID);
  v43 = objc_opt_class(NSNumber);
  v26 = objc_opt_class(NSValue);
  v27 = objc_opt_class(DAKeySharingInvitationData);
  v28 = objc_opt_class(DAKeyBindingAttestationRequestData);
  v29 = objc_opt_class(DAAlishaKeyEncryptedRequest);
  v30 = objc_opt_class(DACarKeySharingMessage);
  v31 = objc_opt_class(DACarKeyGenericCrossPlatformSharingData);
  v32 = objc_opt_class(DACarKeyAdditionalCrossPlatformSharingData);
  v33 = +[NSSet setWithObjects:](NSSet, "setWithObjects:", v52, v50, v48, v46, v44, v43, v26, v27, v28, v29, v30, v31, v32, objc_opt_class(DACarKeyPrivateCrossPlatformSharingData), 0);
  v34 = (void *)objc_claimAutoreleasedReturnValue(v33);
  objc_msgSend(v25, "setClasses:forSelector:argumentIndex:ofReply:", v34, "listSharingInvitationsForKeyIdentifier:callback:", 0, 1);
  objc_msgSend(v25, "setClasses:forSelector:argumentIndex:ofReply:", v34, "listReceivedSharingInvitationsWithCallback:", 0, 1);
  objc_msgSend(v25, "setClasses:forSelector:argumentIndex:ofReply:", v34, "cancelInvitationWithIdentifier:reason:callback:", 0, 1);
  objc_msgSend(v25, "setClasses:forSelector:argumentIndex:ofReply:", v34, "requestBindingAttestationDataForKeyWithIdentifier:callback:", 0, 1);
  objc_msgSend(v25, "setClasses:forSelector:argumentIndex:ofReply:", v34, "getPreTrackRequestForKeyWithIdentifier:callback:", 0, 1);
  objc_msgSend(v25, "setClasses:forSelector:argumentIndex:ofReply:", v34, "ppidRequestForInvitationWithIdentifier:fromMailboxIdentifier:completionHandler:", 0, 1);
  objc_msgSend(v25, "setClasses:forSelector:argumentIndex:ofReply:", v34, "setProductPlanIdentifier:forInvitationIdentifier:completion:", 0, 0);
  objc_msgSend(v25, "setClasses:forSelector:argumentIndex:ofReply:", v34, "remoteTerminateKeys:nodeGroupIdentifiers:treeGroupIdentifiers:adminKey:callback:", 0, 1);
  objc_msgSend(v25, "setClasses:forSelector:argumentIndex:ofReply:", v34, "hasUpgradeAvailableForKeyWithIdentifier:versionType:versions:completionHandler:", 2, 0);
  objc_msgSend(v25, "setClasses:forSelector:argumentIndex:ofReply:", v34, "hasUpgradeAvailableForKeyWithIdentifier:versionType:versions:completionHandler:", 0, 1);
  objc_msgSend(v62, "setInterface:forSelector:argumentIndex:ofReply:", v25, "queueManagementSession:callback:", 0, 1);
  v58 = objc_opt_class(NSArray);
  v57 = objc_opt_class(NSString);
  v35 = objc_opt_class(NSData);
  v36 = objc_opt_class(NSError);
  v37 = objc_opt_class(NSUUID);
  v38 = objc_opt_class(NSNumber);
  v39 = objc_opt_class(DAKeyInformation);
  v40 = +[NSSet setWithObjects:](NSSet, "setWithObjects:", v58, v57, v35, v36, v37, v38, v39, objc_opt_class(DAAlishaKeyEncryptedRequest), 0);
  v41 = (void *)objc_claimAutoreleasedReturnValue(v40);
  objc_msgSend(v62, "setClasses:forSelector:argumentIndex:ofReply:", v41, "registerFriendSideSharingTestCompletion:", 0, 1);

  return v62;
}

@end
